name: Build & Deploy CrownCore
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        run: mvn -U -B clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CrownCore-jar
          path: crowncore/target/CrownCore-*.jar

      - name: Deploy via SFTP (to /home/container/plugins)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USER }}
          server:   ${{ secrets.SFTP_HOST }}
          port:     ${{ secrets.SFTP_PORT }}
          password: ${{ secrets.SFTP_PASS }}
          local_path: 'crowncore/target/CrownCore-*.jar'
          remote_path: '/home/container/plugins/'
          sftp_only: true
